package jtextvalidar;

/**
 * Este es el panel de configuración cuando se despliega la opción desde el editor de propiedades del componente
 * 
 * Es necesario devolver el valor de la propiedad
 * 
 * @author davibern
 * @version 1.0
 */
public class ValidarTextoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ValidarTextoPanel
     */
    public ValidarTextoPanel() {
        initComponents();
    }
    
    /**
     * Método que devuelve el valor seleccionado en el combobox. 
     * Este valor es el que se pasará mediante un BeanInfo y su editor de propiedades.
     * 
     * @return El valor configurado en el editor de propiedades
     */
    public String getSelectedTypeTextValue() {
        return this.jComboBoxTipos.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipos = new javax.swing.JComboBox<>();

        jLabel1.setText("Tipo de texto a validar: ");

        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entero", "Real", "Texto" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxTipos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
